---
version: '3.7'
services:
  # Service image
  numpydoc-demo:
    image: numpydoc-demo:latest
    build: app
    volumes:
      - type: bind
        source: ./output
        target: /app/doc/build/html
